### ISSUE TITLE
User can view geographies' attribute values in a pop-up or column adjacent to map when geography is selected.

### ISSUE THREAD

**Issue by daragoldberg** [NYCPlanning/labs-regional-viz#9] opened 2018-02-20 21:44 UTC
When user clicks a selectable geography (i.e. municipality, county, subregion), corresponding data in profile window will pull up.

**Comment by daragoldberg** [comment] 2018-02-21 14:24
Census tracts cannot be selected

**Comment by chriswhong** [comment] 2018-02-26 16:51
Dupe of #37

**Closed by chriswhong** 2018-02-26 16:51 UTC
Labels: map - data profile
